import React, { Component } from 'react';

class OurPolicies extends Component {
    render() {
        return (
            <div>
                <br /><br /><br /><br /><br /><br />
                <div className="section-title" data-aos="fade-up"> 
                    <h2 className="page-title ">Our Policies</h2>
                    <h6 className="title-description"></h6>
                </div>
                <div className="col-lg-4 col-md-6 d-flex align-items-stretch" data-aos="fade-up">
                    <h2>Our Mission</h2> <br />
                    <p>
                    TO MAXIMIZE THE ROI OF OUR VALUED CLIENTS BY DELIVERING OUTSTANDING PROJECTS THAT SYMBOLIZE A FINE BLEND OF AESTHETICS, FUNCTIONALITY AND ENVIRONMENTAL CARE.

CREATIVE TURNKEY PROJECTS PVT. LTD. IS SPECIALIZING IN DELIVERING ENGINEERING & CONSTRUCTION SERVICES. CREATING NEW BENCHMARKS IN QUALITY AND PROFESSIONALISM, WE HAVE GROWN TO BE ONE OF PUNE’S LEADING TURNKEY PROVIDERS. AT CREATIVE TURNKEY PROJECTS, WE JUST DON’T BUILD CEMENT AND STEEL STRUCTURES; WE PASSIONATELY CREATE LANDMARKS THAT SYMBOLIZE QUALITY, RELIABILITY AND SAFETY.
                    </p>
                </div>
                <div className="col-lg-4 col-md-6 d-flex align-items-stretch" data-aos="fade-up">
                    <h2>Our Vision</h2><br />
                    <p>
                        TO EMERGE AS A MARKET LEADER BY NURTURING A CULTURE OF ETHICS AND EXCELLENCE.
                    </p>
                </div>
                <div className="col-lg-4 col-md-6 d-flex align-items-stretch" data-aos="fade-up">
                    <h2>Quality Policy</h2><br />
                    <p>
                    WE CREATIVE TURNKEY PROJECTS PVT.LTD. ARE IN THE FIELD OF CONSTRUCTION OF CIVIL & MEP WORK FOR CONSTRUCTION OF RESIDENTIAL, INDUSTRIAL AND COMMERCIAL SPACES.

WE ARE COMITTED TO DELIVER THE BEST PRODUCT TO THE SATISFACTION OF OUR VALUED CUSTOMERS.THE CONCERN OF QUALITY IS NURTURED AT EVERY LEVEL OUR WORK FORCE IS QULIFIED AND ADAPTED TO IMPROVISING IN QUALITY NEEDS.

AS STANDING ON STRONG FOUNDATION OF QUALIFICATION AND HAVING LONG EXPERIENCE, WE UNDERSTAND THAT EVERY DAY IS A NEW DAY FOR LEARNING WITHIN THE CONSTRUCTION INDUSTRY.WE WILL ABIDE BY ALL APPLICABLE STATUTORY AND REGULATORY REQUIREMENTS.

WITH THIS IN MIND AS AN EXPERIENCE WE PROVIDE TRAINING TO ALL STAFF MEMBERS, STARTING WITH THE DIRECTORS TO THE WORK FORCE, WHO TOO ARE ACTIVELY INVOLVED, ALONG WITH ALL EMPLOYEES, IN CONTRIBUTION TO QUALITY AND CONTINUAL IMPROVEMENT OF QUALITY MANAGEMENT SYSTEMS.
                    </p>
                </div>
                <div className="col-lg-4 col-md-6 d-flex align-items-stretch" data-aos="fade-up">
                    <h2>ENVIRONMENT, HEALTH AND SAFETY POLICY</h2>
                    <p>
                    WE CREATIVE TURNKEY PROJECTS PVT. LTD. INTENDS TO MEET THESE COMMITMENTS BY ENSURING THAT SAFE WORKING PRACTICE AND PROCEDURES ARE ADOPTED, WHICH COMPLY WITH THE REQUIREMENT OF THE HEALTH AND SAFETY LEGISLATION AND STANDARD PRACTICES IN INDIA.

OUR TEAM IS BOUND TO TAKE CARE OF THEIR OWN AND OTHERS HEALTH AND MAINTAIN A SAFE ENVIRONMENT AT WORK.

ALL EMPLOYEES OF CREATIVE TURNKEY PROJECTS PVT. LTD .  ARE REQUIRED TO:

ENCOURAGE SAFE BEHAVING AMONG THEIR COLLEAGUES.
PARTICIPATE ACTIVELY IN SAFETY PROGRAM AND PUT THE REQUIRED KNOWLEDGE IN TO PRACTICE
FOLLOW DEFINED PROCEDURES WITH SELF-DISCIPLINE AND WORK SAFETY AT ALL TIMES.
TAKE APPROPRIATE ACTIONS TO PROTECT AIR, WATER AND ANIMAL & PLANET LIFE.
                    </p>
                </div>
            </div>
        );
    }
}

export default OurPolicies;